Support generic vault request params
teamforage/forage-android-sdk pull request #152
Opened 2024-01-09 22:28 UTC by djoksimo

## What

- Add support for generic `BaseVaultRequestParams`
- [x] Fix broken unit tests

## Why

- Easier to support pos-specific params while reusing existing facilities

## Test Plan

- ✅ Updated unit tests to use the new generic params

## Demo

## How

Can be merged as-is and other branches for POS refund + balance will build on top of these changes

2024-01-09 23:38 UTC, djoksimo commented on forage-android/src/main/java/com/joinforage/forage/android/network/data/BaseVaultRequestParams.kt
> +    }
`data classes` do not support inheritance.

The overridden `equals` and `hashcode` are needed when `BaseVaultRequestParams` is used inside a `Map` (like in our unit tests, and possible other places in the future).

Open to learning about alternative workarounds.

2024-01-10 14:45 UTC, dleis612 requested changes

2024-01-10 14:45 UTC, dleis612 commented on forage-android/src/main/java/com/joinforage/forage/android/collect/VGSPinCollector.kt
> +        internal fun buildRequestBody(requestBodyParams: BaseVaultRequestParams): HashMap<String, Any> {
Nice :)

2024-01-10 14:45 UTC, dleis612 commented on forage-android/src/main/java/com/joinforage/forage/android/network/data/CapturePaymentRepository.kt
>      private suspend fun submitPaymentCapture(
I think this signature needs `<T : BaseVaultRequestParams>`

2024-01-10 15:44 UTC, dleis612 approved these changes

2024-01-10 16:04 UTC, devinmorgan approved these changes
PR looks good! One thing I wanted to clarify:

From what I can tell, this PR only updates `VGSPinCollector` shuttle the the pos related data into the proxy request and this PR does not update the `BTPinCollector` to do the same. Is that correct?

2024-01-11 14:50 UTC, merged