[FX-1033] Add deferred refund endpoint to terminal SDK
teamforage/forage-android-sdk pull request #200
Opened 2024-02-05 16:30 UTC by dleis612

## What
Add the deferred refund endpoint to the Android SDK for Toast to use.

## Test Plan

- ✅ I've added unit tests for this change.

## How
Can be released as is.

2024-02-14 01:51 UTC, devinmorgan reviewed
Had a look through it and it seems fine to me! Let me know when you need a +1 and I'll mark it as approved!

2024-02-16 20:15 UTC, evanfreeze commented
Verified this on staging by checking out the branch and roughing out some UI to trigger it in the cert app — it works 👍🏻

2024-02-20 17:29 UTC, djoksimo requested changes
Looks great! Left one comment about using the `Pos` prefix, but everything else LGTM.

2024-02-20 17:29 UTC, djoksimo commented on forage-android/src/main/java/com/joinforage/forage/android/ForageSDKInterface.kt
> +data class DeferPosPaymentRefundParams(
the other public POS-specific `data class`-es are prefixed with `Pos`. 
```suggestion
data class PosDeferPaymentRefundParams(
```

2024-02-22 15:19 UTC, merged