SYM-108
teamforage/forage-android-sdk pull request #78
Opened 2023-08-29 11:19 UTC by djordje-mladenovic

Fields for inputHeight and inputWidth as well as elementHeight and elementWidth are exposed for both BT and VGS PIN fields

2023-08-29 19:04 UTC, devinmorgan requested changes
Nice work so far, Djordje. Here are a couple of changes I was hoping you could make:
1. Are the usages of `this` necessary in this PR? When I played around with it locally, they could be dropped. For example, prefer `getDemiensionPixelSize(...)` instead of `this.getDemiensionPixelSize(...)` to conform to the current conventions
2. The lint check seems to be failing. Hopefully, all of the lining issues will be fixed if you run `./gradlew spotlessApply`. This is mentioned in [the README_DEV.md](https://github.com/teamforage/forage-android-sdk/blob/687f8661442f82e96dd26bbfd2f5748e6b000224/README_DEV.md?plain=1#L91) for your reference.
3. Can you please include screenshots showcasing this [ticket's acceptance criteria](https://linear.app/joinforage/issue/SYM-108/android-styling-changes-enable-customization-of-styling-of-pin-input):
    - [x] BasisTheory - PIN Input field's width is smaller than the Forage logo's width 
    - [x] VGS - PIN Input field's width is smaller than the Forage logo's width 
    - [ ] BasisTheory - PIN Input field's width and height are much larger than normal
    - [ ] VGS - PIN Input field's width and height are much larger than normal
4. Can you please update the catalog view of the Sample App by altering the appearance of one of the existing `ForagePINEditText` elements and one of the `ForagePANEditText` elements so that they have non-default values for:
    - [ ] `inputHeight`
    - [ ] `inputWidth`
    - [ ] `elementHeight`
    - [ ] `elementWidth`
    Changing the catalog view in the Sample App will show us how to use the changes you've made so that we can update our documentation accordingly. It will also help us test ourselves locally.

2023-08-30 07:51 UTC, djordje-mladenovic commented
![BTPinFieldSmallerThanLogo](https://github.com/teamforage/forage-android-sdk/assets/108269969/02b171c3-3f46-4525-945a-74bfb3ac34da)
![BTPinFieldLargerThanNormal](https://github.com/teamforage/forage-android-sdk/assets/108269969/f6406934-eb7a-4269-89c4-0d25af63896f)
![VGSPinFieldLargerThanNormal](https://github.com/teamforage/forage-android-sdk/assets/108269969/434f64d3-d936-4cdb-bcd6-a6cd2002b0ab)
![VGSPinFieldSmallerThanLogo](https://github.com/teamforage/forage-android-sdk/assets/108269969/d8e636a6-d575-4bce-9d27-a4c626d7017d)

2023-08-30 13:44 UTC, devinmorgan approved these changes
Thanks for your following changes @djordje-mladenovic! I'll make a follow-up PR that updates the `README.md`. These changes seem to be what we needed!

2023-08-30 13:44 UTC, devinmorgan commented on sample-app/src/main/res/layout/fragment_catalog.xml
Thank you for these changes! It makes it much more clear how styling works in Android

2023-08-30 15:04 UTC, merged